### ISSUE TITLE
Documentation for Webpack is outdated or incomplete

### ISSUE THREAD

**Issue by kevinehosford** [Azure/monaco-kusto#124]
### Description

This project looks great and I'd like to work with it. I've run into issues integrating it though. While I've been able to work through some of them I'm opening this issue to highlight that the documentation for integrating monaco-kusto using webpack seems to be outdated or incomplete.

Here is an example repository that I've set up according to the docs as best as possible: https://github.com/kevinehosford/monaco-kusto-test. Ideally, I'd like to get this example running to see monaco-kusto bundled using webpack, as well as, determine what parts of the documentation need to be updated.

Thanks

**Comment by lucashooten** [comment]
> You'll need to merge the runtime chunk of this entry point with this entry point output chunk to one chunk, and have this one call in getWorkerUrl in step 5.

Please adjust this sentence in the process - really confusing way of stating the end-goal.

**Comment by maxburs** [comment]
I'm closing this issue as stale. Please comment if you'd like to see this re-opened.
