### ISSUE TITLE
Custom function issues

### ISSUE THREAD

**Issue by andresmgot** [Azure/monaco-kusto#189]
### Description

Hi,

I am trying to define a custom similar to the `myFunction2` example here: https://github.com/Azure/monaco-kusto/blob/4fc512597aadf30953e2ae308683ad69d909398e/package/test/custom_schema.json#L1492

This is my definition of the function:

```
    {
      name: '$__timeFilter',
      body: '{     StormEvents     | limit 100 }  ',
      inputParameters: [
        {
          name: 'myLimit',
          type: 'System.Int64',
          cslType: 'long',
          docString: 'Demo for a parameter',
          cslDefaultValue: '6',
        },
      ],
      docString: 'Simple demo function',
    } as any,
```

I have found two issues:

  - My function starts with a dollar sign (`$__timeFilter`). This causes that when I hit "enter" to autocomplete the function the function name gets removed so I end up only with the parenthesis: `( )`
  - My function is supposed to return a boolean but I don't know how to set that. I've tried defining the function with `functionKind: 'System.Boolean'` (and `Boolean` and `bool`) or setting the outputColumns with no luck. I don't see any documentation of how to do that. This causes that the function is detected as an error.

You can see the two issues in the following gif:

![Peek 2022-04-11 18-02](https://user-images.githubusercontent.com/4025665/162782609-18a197d6-3222-4c9f-8953-83f9e3966d9b.gif)

 ### Steps to Reproduce

See the description above. 

 **Expected behavior:** [What you expect to happen]

 **Actual behavior:** [What actually happens]

 **Reproduces how often:** [What percentage of the time does it reproduce?]

 ### System configuration

 monaco-kusto version: 5.0.0
 monaco-editor version: 0.31.1
 Browser:
 OS:

**Comment by andresmgot** [comment]
cc/ @lidermanrony in case you have any feedback

**Comment by izikl** [comment]
Function names (https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/functions/user-defined-functions#function-names) can't start with a dollar, so that can explain the auto-completion behavior.

Regarding the boolean, the function body is `{ StormEvents | limit 100 }`, which returns a table, if it was returning a boolean you could would have used it in a where clause. With your current method something like this could work: 
```
Perf | union <you table returning method>
```

**Comment by andresmgot** [comment]
Thanks @izikl! I was not aware that the body was used to infer the type of the result, that solves the bool error.

For the function name, I understand it's not a valid Kusto function name. To give more context, we are using this package in the Azure Monitor Logs editor for Grafana. In Grafana, we have the concept of "macros". These macros are helper functions that are pre-processed and return, in this case, valid Kusto code. You can see [here](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#azure-resource-graph-macros) some examples.

The interesting thing about the substitution is that it only deletes my function name if the function has parameters. If no `inputParameter` is set, it properly autocompletes the function name. Maybe you can point me to the part of the code that makes this substitution? I could try to give it a try and fix the bug.

Another issue I am facing (sorry to gather all those here) is trying to suggest a function with an optional parameter. From the link above, you can see that the function `$__timeFilter` can have none or one parameter. I guess this is not something possible in Kusto either. If I try to set that up as different functions, I also get an error:

```js
    {
      name: '$__timeFilter',
      body: '{ true }',
      inputParameters: [],
    },
    {
      name: '$__timeFilter',
      body: '{ true }',
      inputParameters: [
        {
          name: 'timeColumn',
          type: 'System.String',
          defaultValue: 'TimeGenerated',
          cslDefaultValue: 'TimeGenerated',
        },
      ],
    },
```

![Screenshot from 2022-04-13 11-42-14](https://user-images.githubusercontent.com/4025665/163148340-482b0d6d-e04b-4926-bf3e-b12bdec97362.png)

Is there a way to do this? Really appreciate the help here.

**Comment by lidermanrony** [comment]
regarding the completion item issue, this following PR should fix it. https://github.com/Azure/monaco-kusto/pull/190

**Comment by andresmgot** [comment]
> re: optional parameters: That doesn't seem to work for me. This is my function definition:
> 
> ```js
>     {
>       name: '$__timeFilter',
>       body: '{ true }',
>       inputParameters: [
>         {
>           name: 'timeColumn',
>           type: 'System.String',
>           defaultValue: 'TimeGenerated',
>           cslDefaultValue: 'TimeGenerated',
>         },
>       ],
>     },
> ```

For the record, it was an issue with the default value definition. I assume that `'TimeGenerated'` was not a valid value? I changed it for an empty string `'""'` and now it can successfully omitted. Thanks for the help here!
