### ISSUE TITLE
Monaco-kusto doesn't support absolute paths

### ISSUE THREAD

**Issue by amitharitan** [Azure/monaco-kusto#195]
Hi I want to load this package on our website, but I am getting into some issues.

The issue I am facing is that when I am trying to load the webworker (workerMain.js) from a blob and I am receiving a lot of errors due to relative path loading.
(I am loading it through a blob because of CORS issue I have on loading scripts).

Once I load it from the blob the KustoWorker is called through a relative path and then the bridge.min etc. I tried to change it to an absolute path in the kustoMode.js and the kustoWorker.js but then the workaccessor doesn’t return.
![image](https://user-images.githubusercontent.com/93866218/169820986-3e83b150-b61f-4dcc-923e-a0c8491f03aa.png)

![image](https://user-images.githubusercontent.com/93866218/169820858-77281b0f-aa90-4462-bacd-191ddcd5711a.png)

kustoMode.js:
![image](https://user-images.githubusercontent.com/93866218/169821140-2aca0cba-348e-4dcf-b3b3-e8ee7db83866.png)

kustoWorker.js:
![image](https://user-images.githubusercontent.com/93866218/169821350-167f7ff6-270a-4d50-aa8c-de76c9463063.png)

**Comment by maxburs** [comment]
Hi @amitharitan, are you still seeing this issue?

We've made a lot of improvements to the esm files we publish. If you're still having trouble I'd take a look at that.

If you need to stick with ADM modules, then a reproduction would be really helpful. If you can provide one then I'd be happy to take a look.
