### ISSUE TITLE
Errors not always rendered

### ISSUE THREAD

**Issue by sobolewsk** [Azure/monaco-kusto#196]
### Description

Syntax/semantic errors are not always renderered. The root cause seems to be [this line](https://github.com/Azure/monaco-kusto/blob/master/package/src/languageService/kustoLanguageService.ts#L690), where `waitForAnalysis` is set `false` in GetDiagnostics, leading to returning only pre-computed results. Removing `false` from the `GetDiagnostics` call fixes the issue. Any idea why `false` is passed there?

 ### Steps to Reproduce

Using the test page from this repo:

 1. Type a few random characters to change `StormEvents` into an invalid data source name in the default query
 2. See that there is no errors rendered
 3. Change the last operator from `count` to `counta`
 4. See that errors are now rendered

 **Expected behavior:** Errors should be rendered always

 **Actual behavior:** Errors are rendered intermittently 

 **Reproduces how often:** 100%

 ### System configuration

 monaco-kusto version: 5.1.3
 monaco-editor version: 0.33.0
 Browser: Chrome
 OS: Mac OS 11.6.2

**Comment by gikoifma** [comment]
Thanks for reporting.
You are right, and this actually is an honest mistake, created a PR to remove the "false" flag.

https://github.com/Azure/monaco-kusto/pull/197

**Comment by sobolewsk** [comment]
Wow, thank you very much for an instant response!
