### ISSUE TITLE
Raw query editor not showing schema of dynamic fields

### ISSUE THREAD

**Issue by mrbar42** [Azure/monaco-kusto#204]
### Description
Raw Query Editor not showing schema of dynamic fields even though query builder does.
Originally reported at https://github.com/grafana/azure-data-explorer-datasource/issues/409 but was referred here.

 ### Steps to Reproduce
1. given an ADX datasource with a table that contains a dynamic field with nested fields
Example:

| Col1         | Col2     | Col3 |
|--------------|-----------|------------|
| value1 | value2      | {count: 1}        |

2. go to "Explore"
3. Make sure that the visual builder shows "Col3.count" in the fields list
4. switch to raw KQL editor
5. type "Col3."
6. The suggestions window doesn't show "count" as an option

 **Expected behavior:** [What you expect to happen]
The visual query builder does show nested fields inside dynamic field so i expected that the raw editor will behave the same.

 **Actual behavior:** [What actually happens]
When writing a query using the raw KQL editor the auto-completion suggestions are not showing nested schema of dynamic fields.

 **Reproduces how often:** [What percentage of the time does it reproduce?]
100%

 ### System configuration

 monaco-kusto version: -
 monaco-editor version: 0.17.0
 Browser: Edge
 OS: macOS

**Comment by maxburs** [comment]
Hi @mrbar42, are you still seeing this issue?
