### ISSUE TITLE
kusto.javascript.client.min.js Information Disclosure 

### ISSUE THREAD

**Issue by raiajithkumarr** [Azure/monaco-kusto#265]
Hi Team,
We got one security issue regarding this kusto.javascript.client.min.js file.
In this file we have we have below statements which are seems to be username and password

namic](./scalar-data-types/dynamic.md) that included the URL components: Scheme, Host, Port, Path, Username, Password, Query Parameters, Fragment.",'```\r\nT | extend Result = parse_url("scheme://**username:password@host:1234**/this/is/a/path?k1=v1&k2=v2#fragment")

Could you please confirm whether it is NOT a security issue and expected statement here (it is a just reference statement).

**Comment by raiajithkumarr** [comment]
Hi @Team
Please update on this.

**Comment by maxburs** [comment]
Is this what you're referring to?

<img width="1793" alt="image" src="https://user-images.githubusercontent.com/8890312/230506622-9beea11d-3db5-44a5-a227-f4654cd71a02.png">

It's part of a doc comment used in the language server and is not a security issue.

**Comment by maxburs** [comment]
@raiajithkumarr If you still have concerns please comment and I'll re-open the issue.
