### ISSUE TITLE
installing @kusto/monaco-editor via npm not working

### ISSUE THREAD

**Issue by JamesAHowieson** [Azure/monaco-kusto#286]
### Description

When trying to install the @kusto/monaco-editor via npm, it is unable to find that package in the registry

Output from running NPM:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@kusto/monaco-editor'
1 verbose cli ]
2 info using npm@6.14.18
3 info using node@v14.21.3
4 verbose npm-session b5dc8eef4439a02e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@kusto%2fmonaco-editor 803ms
8 http fetch GET 404 https://registry.npmjs.org/@kusto%2fmonaco-editor 196ms
9 silly fetchPackageMetaData error for @kusto/monaco-editor@latest 404 Not Found - GET https://registry.npmjs.org/@kusto%2fmonaco-editor - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 4775ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@kusto%2fmonaco-editor - Not found
12 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:117:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
13 verbose statusCode 404
14 verbose pkgid @kusto/monaco-editor@latest
15 verbose cwd /workspaces/clarity-internal
16 verbose Linux 5.15.49-linuxkit
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@kusto/monaco-editor"
18 verbose node v14.21.3
19 verbose npm  v6.14.18
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@kusto%2fmonaco-editor - Not found
22 error 404
23 error 404 '@kusto/monaco-editor@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

**Comment by maxburs** [comment]
It looks like you tried to install @kusto/monaco-editor, we're publishing @kusto/monaco-kusto
