### ISSUE TITLE
Monaco Editor with Kusto query syntax support in Angular 16

### ISSUE THREAD

**Issue by samhoamt** [Azure/monaco-kusto#355]
### Description

I'm working on the project that allow user to write kql. The project is using Angular 16.

I'm using [ngx-monaco-editor-v2](https://www.npmjs.com/package/ngx-monaco-editor-v2) and [@kusto/monaco-kusto](https://www.npmjs.com/package/@kusto/monaco-kusto) but unfortunately not manage to work. Keep getting error.

Is there any documentation or sample code for Angular 16?

**Comment by maxburs** [comment]
Hi Samhoamt,

We don't have any angular examples at this time, sorry.

You might be able to get it working by copying most of our React/ESM example here (1) https://github.com/Azure/monaco-kusto/blob/master/samples/esm-webpack-react/src/index.js, and following a guide for using a vanilla .js library with Angualar.

After looking at the config for a moment, I think ngx-monaco-editor-v2 is using AMD modules. If you want to keep using it, then I'd take a look at our AMD example and see if you can't figure out how to apply what in that to the libraries config.

If you can share an error message I might be able to point you in the right direction.
