### ISSUE TITLE
Integrate monaco-kusto in a react app created using CRA.

### ISSUE THREAD

**Issue by rasikat86** [Azure/monaco-kusto#360]
### Description

Hello, 
I want to integrate Kusto Language support in my React App Monaco Editor. I have bootstrapped the App using CRA. I referred to the sample [here](https://github.com/Azure/monaco-kusto/tree/master/samples/esm-webpack-react) and used `react-app-rewired` to override my webpack configuration.  Here is the relevant section of webpack config - 

```
module.exports = function override(config, env) {
  const cwd = path.resolve();
  config.resolve = {
    alias: {
      ...config.alias,
    'vs/language/kusto/kustoMode': 'kustoMode',
    'bridge.min': '@kusto/monaco-kusto/release/esm/bridge.min',
    'kusto.javascript.client.min': '@kusto/monaco-kusto/release/esm/kusto.javascript.client.min.js',
    'Kusto.Language.Bridge.min': '@kusto/monaco-kusto/release/esm/Kusto.Language.Bridge.min.js',
    'Kusto': '@kusto/monaco-kusto/release/esm/Kusto.Language.Bridge.min.js',
    'monaco.contribution': path.resolve(__dirname, '../node_modules/@kusto/monaco-kusto/release/esm/monaco.contribution.js')
    }
  };
...
```

This does not work and I get the error `Cannot find module 'monaco.contribution' or its corresponding type declarations.`. 

Does monaco-kusto work with CRA and `react-app-rewired`? If yes, it will be helpful to have a sample of the same added to the samples section. 

### System configuration

"@kusto/monaco-kusto": "2.1.14",
"@monaco-editor/react": "^4.5.2",
"monaco-editor": "^0.44.0",

**Comment by maxburs** [comment]
Hi rasikat86,

You don't need to use react-app-rewired to get the monaco editor working on CRA anymore. The example you linked to uses Webpack 5's webworker support to avoid using the plugin. You can see how we're doing this here: https://github.com/Azure/monaco-kusto/blob/b2ad6cb095c3107fac59ecea5f1890e2ea5cfedd/samples/esm-webpack-react/src/index.js#L27

What's in that example will work with the latest versions of CRA as long as you don't add any special configuration.

> Does monaco-kusto work with CRA and react-app-rewired? If yes, it will be helpful to have a sample of the same added to the samples section.

The sample actually used to use CRA. We switched to Webpack to reduce our install time. You can see it here: 
https://github.com/Azure/monaco-kusto/tree/e3896c8cb858c1b2fddb8d10fe89e43fc553e4e9/samples/react

Let me know if that helps.

**Comment by rasikat86** [comment]
Hi @maxburs,

Thanks for the clarification. I can confirm that I was able to achieve kusto integration using Webpack 5's webworker support. However, I still had to use react-app-rewired for bypassing the error regarding `fs.resolve` .

**Comment by maxburs** [comment]
> However, I still had to use react-app-rewired for bypassing the error regarding fs.resolve .

You're right, forgot about that, sorry. I agree that that's more of an issue with us than with Creact React App. I'll reactive this issue and rename it to track that because there's no public repo for @kusto/language-service

**Comment by maxburs** [comment]
Closing this issue again in favor of a new one with a description specific to `require("fs")` calls: #388
