### ISSUE TITLE
Release does not have esm files

### ISSUE THREAD

**Issue by asakiran13** [Azure/monaco-kusto#378]
### Description

![image](https://github.com/Azure/monaco-kusto/assets/10269665/45f371da-906f-4f0f-9d3b-66709fa60f03)

Release does not have esm files

### Steps to Reproduce

npm install @kusto/monaco-kusto

### System configuration

monaco-kusto version: 0.0.65
monaco-editor version: 0.44.0
Browser:
OS:

**Comment by maxburs** [comment]
Hi Asakiran,

> monaco-kusto version: 0.0.65

Could you be looking at a different packages version number? I don't see anything on NPM with that version:

<img width="550" alt="image" src="https://github.com/Azure/monaco-kusto/assets/8890312/51236b29-9b07-4a7e-9615-202d27768687">
https://www.npmjs.com/package/@kusto/monaco-kusto/v/10.0.7?activeTab=versions

I checked our last few releases and I'm seeing all the files:

<img width="371" alt="image" src="https://github.com/Azure/monaco-kusto/assets/8890312/52a753e9-fadc-46dc-9122-6f492cdc08e5">
https://yarnpkg.com/package?q=%40kusto%2Fmonaco-kusto&name=%40kusto%2Fmonaco-kusto&version=10.0.7
