### ISSUE TITLE
Compile failure in react project.

### ISSUE THREAD

**Issue by fondoger** [Azure/monaco-kusto#382]
Tried the sample:

```log
ERROR in ./node_modules/@kusto/language-service/bridge.min.js 26013:40-53
Module not found: Error: Can't resolve 'fs' in 'C:\repo\my-react-project\node_modules\@kusto\language-service'

webpack compiled with 1 error and 1 warning
No issues found.
```

Could you please give us a minimal sample for projects created with `create-react-app`?

### System configuration

monaco-kusto version: 10.0.7
monaco-editor version: 0.44.0
Browser:
OS:

**Comment by fondoger** [comment]
I believe there is a bug in @kusto/language-service/bridge.js

`requrie("fs")` should be changed to `__non_webpack_require__("fs")`. 
https://stackoverflow.com/questions/52581441/ignoring-specific-requires-in-webpack

![image](https://github.com/Azure/monaco-kusto/assets/22270677/eb1bd007-f462-49d6-b32a-182b102cd63e)

**Comment by maxburs** [comment]
If you're trying to get the esm version working then esm-webpack-react is the closest example.

That example configures webpack to ignore the import:
<img width="1032" alt="image" src="https://github.com/Azure/monaco-kusto/assets/8890312/886ecb76-ce21-418b-b3b7-05f4577ccb93">

I'm not aware of any way to get Create React App to have this behavior without either ejecting or using something like craco[^1] to customize the config.

I agree that this is a bug in @kusto/language-server, but I'm afraid I don't expect to see it fixed anytime soon.

[^1]: https://github.com/dilanx/craco

I agree that the `require` call in the

**Comment by maxburs** [comment]
Created an issue to track this: #388
