### ISSUE TITLE
samples/esm-webpack-react doest run

### ISSUE THREAD

**Issue by sethreidnz** [Azure/monaco-kusto#389]
### Description

I am working on using this in project and trying to get the esm-webpack sample working and getting errors.

### Steps to Reproduce

1. Clone the repo
2. Run `yarn install`
3. Run `cd samples/esm-webpack-react`
4. Run `yarn serve`

**Expected behavior:**

To be able to see the sample running in the browser

**Actual behavior:** 

It launches the server but I get the following error:

![CleanShot 2023-11-29 at 10 38 08](https://github.com/Azure/monaco-kusto/assets/4713713/bc291076-9762-4a17-a7c6-8ff0a8ca7f6f)

### System configuration

"@kusto/monaco-kusto": "workspace:*",
"monaco-editor": "^0.41.0",
Browser: Edge
OS: Mac

**Comment by maxburs** [comment]
Hi Seth,

The README.md is incomplete. You'll need to run `yarn build` in `/package` first. I've opened a PR to carity this, and to mention `yarn` and Node 20:

https://github.com/Azure/monaco-kusto/blob/b7cd18c170731f1c66d14622262ebe340eea3e3a/samples/esm-webpack-react/README.md

**Comment by sethreidnz** [comment]
Ah ok thanks for that. But just so that I understand, there are build steps included in the /package `yarn build` that are not included in the sample that are required to get it working? 

I'm guessing at the least I will need to do something like `copyMonacoFilesAMD.js`. Are there other things happening in the package directory build that the sample relies on?

**Comment by maxburs** [comment]
> But just so that I understand, there are build steps included in the /package yarn build that are not included in the sample that are required to get it working?

That's right. The /package build step isn't required if you're not working in this repo. It's required here because we're using a local build of the package.

> I'm guessing at the least I will need to do something like copyMonacoFilesAMD.js. 

copyMonacoFilesAMD.js is only required if you wish to resolve monaco with AMD files (I don't recommend). If you do with to do this, then copyMonacoFilesAMD.js might help. It's included in the published package.

> Are there other things happening in the package directory build that the sample relies on?

What do you mean by "relies on"?

If you copy/paste the example code out of the repo, and update the @kusto/monaco-kusto dependency to resolve a published package, it should work without changes.

**Comment by sethreidnz** [comment]
> If you copy/paste the example code out of the repo, and update the @kusto/monaco-kusto dependency to resolve a published package, it should work without changes.

This is exactly what I did the first time that I did it. I'll try it again and report back. What I meant by my question though is the sample appears to not work unless you run a command in the /package folder, which is what gave me the impression it wasn't standalone.

I've been trying to get it working with Vite and would happily do a contrib of another sample if I can get this working. But honestly struggling quite a bit. I wonder if you would help me if I shared my progress so far? This is in service of an internal Microsoft project fyi.

**Comment by sethreidnz** [comment]
I got it working with vite! Would you want a PR that adds another sample for a react+vite based project? Happy to do so if you want. Here is my example

https://github.com/sethreidnz/vite-monaco-kusto-example

**Comment by maxburs** [comment]
> Happy to do so if you want. Here is my example

That would be great! We test that all samples start and load the language server in CI, so a sample would ensure we don't accidentally break you.

If you do open a PR with a working sample, please give me push permission to the branch and I'll make any necessary tweaks to get it merged.

**Comment by sethreidnz** [comment]
> > Happy to do so if you want. Here is my example
> 
> That would be great! We test that all samples start and load the language server in CI, so a sample would ensure we don't accidentally break you.
> 
> If you do open a PR with a working sample, please give me push permission to the branch and I'll make any necessary tweaks to get it merged.

Great I'll have a look at doing this shortly! I have got it almost there but struggling a little with the worker url stuff which is done a little different in rollup than webpack. Not sure if you really know how to help there but I'll create a branch and you can have a look and see what you can figure out.
