### ISSUE TITLE
kustoMode.js:120 Uncaught TypeError: Cannot read property 'IntelliSense' of undefined

### ISSUE THREAD

**Issue by githubavi** [Azure/monaco-kusto#63]
### Description

 Hi, I have cloned the latest repo from master branch and trying to test "/test/index.html" page with "serve ." command. But when the editor is being loaded, I am getting this below error and the intellisense not working.

![image](https://user-images.githubusercontent.com/3995838/74587435-35300c80-5018-11ea-85a6-f795b526be7e.png)

Here is the index.html file, I am trying to test,

[index.html.txt](https://github.com/Azure/monaco-kusto/files/4208420/index.html.txt)

Please help me out to resolve this issue.

 ### Steps to Reproduce

 [Steps or usage snippet reproducing the issue]

 1. [First Step]
 2. [Second Step]
 3. [and so on...]

 ```
 <snippet>
 ```

 **Expected behavior:** [What you expect to happen]

 **Actual behavior:** [What actually happens]

 **Reproduces how often:** [What percentage of the time does it reproduce?]

 ### System configuration

 monaco-kusto version: 0.x.y
 monaco-editor version: 0.X.Y
 Browser:
 OS:

**Comment by maxburs** [comment]
Closing issue as stale. If anyone is still experiencing this, please comment and I'll re-open it.
