### ISSUE TITLE
Exception: e is null eLPx/I</e.prototype.parseDocumentV2

### ISSUE THREAD

**Issue by rogarfel** [Azure/monaco-kusto#85]
In Logs protal we are getting this exception:
from: parseDocumentV2 method.

we are using:     "monaco-editor": "0.15.4",

e is null eLPx/I</e.prototype.parseDocumentV2@https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.eeaa2ae3e24076c77878_adf5893245a341aab530.js:18:1675178 eLPx/I</e.prototype.doCompleteV2@https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.eeaa2ae3e24076c77878_adf5893245a341aab530.js:18:1654319 eLPx/I</e.prototype.doComplete@https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.eeaa2ae3e24076c77878_adf5893245a341aab530.js:18:1654220 eLPx/D</e.prototype.doComplete@https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.eeaa2ae3e24076c77878_adf5893245a341aab530.js:18:1680252 2U0d/</K</t.prototype.fmr@https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.eeaa2ae3e24076c77878_adf5893245a341aab530.js:4:8369 sj9p/</S</t.prototype._handleMessage@https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.eeaa2ae3e24076c77878_adf5893245a341aab530.js:71:32371 handleMessage@https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.eeaa2ae3e24076c77878_adf5893245a341aab530.js:71:32004 sj9p/</m</t.prototype._handleMessage@https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.eeaa2ae3e24076c77878_adf5893245a341aab530.js:71:30273 sj9p/</m</t.prototype.handleMessage@https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.eeaa2ae3e24076c77878_adf5893245a341aab530.js:71:29841 sj9p/</S</t.prototype.onmessage@https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.eeaa2ae3e24076c77878_adf5893245a341aab530.js:71:32083 i/self.onmessage@https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.eeaa2ae3e24076c77878_adf5893245a341aab530.js:18:1645517 at e/this.unexpectedErrorHandler/<
--

**Comment by lidermanrony** [comment]
Hi folks.
can you please provide:
1. repro steps
2. impact on user

**Comment by maxburs** [comment]
Closing issue as stale. If anyone is still experiencing this, please comment and I'll re-open it.
