### ISSUE TITLE
Exception: Cannot read property 'getText' of null TypeError: Cannot read property 'getText' of null at e.parseDocumentV2 

### ISSUE THREAD

**Issue by violetVo** [Azure/monaco-kusto#86]
### Description

Get the following exceptions in Logs blade:
Cannot read property 'getText' of null TypeError: Cannot read property 'getText' of null at e.parseDocumentV2 (https://logsextension.hosting.portal.azure.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:18:1675235) at e.doCompleteV2 (https://logsextension.hosting.portal.azure.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:18:1654319) at e.doComplete (https://logsextension.hosting.portal.azure.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:18:1654220) at e.doComplete (https://logsextension.hosting.portal.azure.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:18:1680252) at t.fmr (https://logsextension.hosting.portal.azure.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:4:8369) at t._handleMessage (https://logsextension.hosting.portal.azure.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:71:32371) at Object.handleMessage (https://logsextension.hosting.portal.azure.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:71:32004) at t._handleMessage (https://logsextension.hosting.portal.azure.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:71:30273) at t.handleMessage (https://logsextension.hosting.portal.azure.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:71:29841) at t.onmessage (https://logsextension.hosting.portal.azure.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:71:32083) at e.parseDocumentV2

 ### System configuration

 monaco-kusto version: 2.1.4
 monaco-editor version: 0.15.4
 Browser: Chrome 83.0

**Comment by lidermanrony** [comment]
Hi folks.
can you please provide:
1. repro steps
2. impact on user
